name: Unity Build

on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Client/UnityCI/Library
          key: Library-${{ runner.os }}-${{ hashFiles('Client/UnityCI/Assets/**', 'Client/UnityCI/ProjectSettings/**') }}

      - name: Activate Unity License
        uses: game-ci/unity-activate@v4
        with:
          unityVersion: 6000.0.24f1
          username: ${{ secrets.UNITY_EMAIL }}
          password: ${{ secrets.UNITY_PASSWORD }}

      - name: Build project
        uses: game-ci/unity-builder@v4
        with:
          projectPath: .
          unityVersion: 6000.0.24f1
          targetPlatform: StandaloneWindows64
        working-directory: Client/UnityCI

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: Client/UnityCI/build/StandaloneWindows64
