name: Unity Build

on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # (선택) Library·Gradle 캐시 – 빌드 속도 향상
    - name: Cache Unity Library
      uses: actions/cache@v4
      with:
        path: Client/UnityCI/Library
        key: Library-${{ runner.os }}-${{ hashFiles('Client/UnityCI/Assets/**', 'Client/UnityCI/ProjectSettings/**') }}

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: Gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

    # ▶ 1단계: External Dependency Manager 강제 실행
    - name: Resolve Android dependencies (EDM4U)
      uses: game-ci/unity-builder@v4
      env:
        UNITY_LICENSE:  ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        projectPath: Client/UnityCI
        unityVersion: 6000.0.24f1       # 사용 중인 Unity 버전
        targetPlatform: StandaloneLinux64  # 실제 빌드는 하지 않고, 에디터만 실행
        customParameters: -executeMethod GooglePlayServices.PlayServicesResolver.MenuResolve

    # ▶ 2단계: Android 빌드
    - name: Build project
      uses: game-ci/unity-builder@v4
      env:
        UNITY_LICENSE:  ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        projectPath: Client/UnityCI
        unityVersion: 6000.0.24f1
        targetPlatform: Android
        androidExportType: androidPackage
        androidKeystoreName: user.keystore
        androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        androidKeyaliasName: ${{ secrets.ANDROID_KEY_ALIAS }}
        androidKeyaliasPass: ${{ secrets.ANDROID_KEY_PASSWORD }}

    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: Build
        path: build/Android
